############################################################
# ICS-OS Development
############################################################
FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y build-essential nasm qemu-kvm tcc git gcc-multilib

RUN mkdir -p /home/ics-os

